const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  SALES_MANAGER: 'SALES_MANAGER',
  SALES_EXECUTIVE: 'SALES_EXECUTIVE',
  PURCHASE_MANAGER: 'PURCHASE_MANAGER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  ACCOUNTANT: 'ACCOUNTANT',
  HR_MANAGER: 'HR_MANAGER',
  PRODUCTION_MANAGER: 'PRODUCTION_MANAGER',
  CUSTOMER: 'CUSTOMER',
  EMPLOYEE: 'EMPLOYEE',
};

const ALL_PERMISSIONS = [
  'dashboard:read',
  'users:read',
  'users:write',
  'roles:read',
  'roles:write',
  'products:read',
  'products:write',
  'inventory:read',
  'inventory:write',
  'customers:read',
  'customers:write',
  'suppliers:read',
  'suppliers:write',
  'sales:read',
  'sales:write',
  'purchases:read',
  'purchases:write',
  'grn:read',
  'grn:write',
  'invoices:read',
  'invoices:write',
  'payments:read',
  'payments:write',
  'accounting:read',
  'accounting:write',
  'expenses:read',
  'expenses:write',
  'hr:read',
  'hr:write',
  'attendance:read',
  'attendance:write',
  'leave:read',
  'leave:write',
  'payroll:read',
  'payroll:write',
  'crm:read',
  'crm:write',
  'manufacturing:read',
  'manufacturing:write',
  'qc:read',
  'qc:write',
  'reports:read',
  'notifications:read',
  'audit:read',
  'settings:read',
  'settings:write',
  'portal:dashboard',
  'portal:profile',
  'portal:products',
  'portal:orders',
  'portal:invoices',
  'portal:payments',
  'portal:notifications',
  'portal:support',
];

const CUSTOMER_PERMISSIONS = [
  'portal:dashboard',
  'portal:profile',
  'portal:products',
  'portal:orders',
  'portal:invoices',
  'portal:payments',
  'portal:notifications',
  'portal:support',
];

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [...ALL_PERMISSIONS],
  [ROLES.ADMIN]: [...ALL_PERMISSIONS],
  [ROLES.SALES_MANAGER]: [
    'dashboard:read',
    'products:read',
    'inventory:read',
    'customers:read',
    'customers:write',
    'sales:read',
    'sales:write',
    'invoices:read',
    'invoices:write',
    'payments:read',
    'payments:write',
    'crm:read',
    'crm:write',
    'reports:read',
    'notifications:read',
    'attendance:self',
  ],
  [ROLES.SALES_EXECUTIVE]: [
    'dashboard:read',
    'products:read',
    'inventory:read',
    'customers:read',
    'customers:write',
    'sales:read',
    'sales:write',
    'invoices:read',
    'invoices:write',
    'payments:read',
    'crm:read',
    'crm:write',
    'notifications:read',
    'attendance:self',
  ],
  [ROLES.PURCHASE_MANAGER]: [
    'dashboard:read',
    'products:read',
    'inventory:read',
    'suppliers:read',
    'suppliers:write',
    'purchases:read',
    'purchases:write',
    'grn:read',
    'grn:write',
    'reports:read',
    'notifications:read',
    'attendance:self',
  ],
  [ROLES.INVENTORY_MANAGER]: [
    'dashboard:read',
    'products:read',
    'products:write',
    'inventory:read',
    'inventory:write',
    'grn:read',
    'grn:write',
    'reports:read',
    'notifications:read',
    'attendance:self',
  ],
  [ROLES.ACCOUNTANT]: [
    'dashboard:read',
    'invoices:read',
    'invoices:write',
    'payments:read',
    'payments:write',
    'expenses:read',
    'expenses:write',
    'accounting:read',
    'accounting:write',
    'reports:read',
    'notifications:read',
    'attendance:self',
  ],
  [ROLES.HR_MANAGER]: [
    'dashboard:read',
    'hr:read',
    'hr:write',
    'attendance:read',
    'attendance:write',
    'leave:read',
    'leave:write',
    'payroll:read',
    'payroll:write',
    'reports:read',
    'notifications:read',
    'attendance:self',
  ],
  [ROLES.PRODUCTION_MANAGER]: [
    'dashboard:read',
    'products:read',
    'inventory:read',
    'manufacturing:read',
    'manufacturing:write',
    'qc:read',
    'qc:write',
    'reports:read',
    'notifications:read',
    'attendance:self',
  ],
  [ROLES.CUSTOMER]: [...CUSTOMER_PERMISSIONS],
  [ROLES.EMPLOYEE]: [
    'dashboard:read',
    'products:read',
    'inventory:read',
    'customers:read',
    'sales:read',
    'sales:write',
    'crm:read',
    'crm:write',
    'notifications:read',
    'attendance:self',
  ],
};

const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.ADMIN];
const CUSTOMER_ROLES = [ROLES.CUSTOMER];
const ATTENDANCE_ELIGIBLE_ROLES = [
  ROLES.EMPLOYEE,
  ROLES.SALES_MANAGER,
  ROLES.SALES_EXECUTIVE,
  ROLES.PURCHASE_MANAGER,
  ROLES.INVENTORY_MANAGER,
  ROLES.ACCOUNTANT,
  ROLES.HR_MANAGER,
  ROLES.PRODUCTION_MANAGER,
];

function isAdminRole(roleName) {
  return ADMIN_ROLES.includes(String(roleName || '').toUpperCase());
}

function isCustomerRole(roleName) {
  return CUSTOMER_ROLES.includes(String(roleName || '').toUpperCase());
}

function isAttendanceEligibleRole(roleName) {
  return ATTENDANCE_ELIGIBLE_ROLES.includes(String(roleName || '').toUpperCase());
}

module.exports = {
  ROLES,
  ALL_PERMISSIONS,
  CUSTOMER_PERMISSIONS,
  ROLE_PERMISSIONS,
  ADMIN_ROLES,
  ATTENDANCE_ELIGIBLE_ROLES,
  isAdminRole,
  isCustomerRole,
  isAttendanceEligibleRole,
};
